version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    env_file:
      - ./envs/.env
    depends_on:
      - api-db
  api-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    volumes:
      - api-db-data:/var/lib/postgresql/data
    env_file:
      - ./envs/.env.postgres
    ports:
      - 5434:5432

volumes:
  api-db-data:
